#!/bin/bash

# INSTRUCCIONES PARA DEPLOYMENT DE AUTENTICACIÓN EN EL VPS
# =========================================================

echo "=========================================="
echo "   DEPLOYMENT DE AUTENTICACIÓN EN VPS"
echo "=========================================="
echo ""
echo "⚠️  IMPORTANTE: Ejecutar estos comandos EN EL VPS (168.181.185.42)"
echo ""

# Token generado
TOKEN="a955acdeced6398e653f68557ade71830e709b7ece72eec40ab0abfdf72e93cd"

echo "🔐 Token de autenticación:"
echo "$TOKEN"
echo ""
echo "=========================================="
echo "PASO 1: Conectar al VPS"
echo "=========================================="
echo ""
echo "ssh root@reimon.dev -p 5591"
echo ""
echo "=========================================="
echo "PASO 2: Copiar archivos al VPS"
echo "=========================================="
echo ""
echo "# Desde tu máquina local, copiar archivos actualizados:"
echo "scp -P 5591 /home/reimon/greenhouse/backend-websocket-update/server.js root@reimon.dev:/tmp/"
echo "scp -P 5591 /home/reimon/greenhouse/backend-websocket-update/.env root@reimon.dev:/tmp/"
echo ""
echo "=========================================="
echo "PASO 3: En el VPS, mover archivos y reiniciar"
echo "=========================================="
echo ""
echo "# Encontrar el directorio del backend"
echo "pm2 list  # Ver el nombre del proceso y directorio"
echo ""
echo "# Mover archivos (ajustar ruta según tu configuración)"
echo "sudo cp /tmp/server.js /ruta/a/tu/backend/server.js"
echo "sudo cp /tmp/.env /ruta/a/tu/backend/.env"
echo ""
echo "# Reiniciar servicio"
echo "pm2 restart greenhouse-backend  # o el nombre que uses"
echo ""
echo "=========================================="
echo "PASO 4: Verificar en VPS"
echo "=========================================="
echo ""
echo "# Ver logs"
echo "pm2 logs greenhouse-backend --lines 50"
echo ""
echo "# Deberías ver:"
echo "✓ Authentication successful for device: ESP32_GREENHOUSE_01"
echo ""
echo "=========================================="
echo "PASO 5: Verificar desde tu máquina local"
echo "=========================================="
echo ""
echo "# Monitorear ESP32"
echo "cd /home/reimon/greenhouse"
echo "pio device monitor"
echo ""
echo "# Deberías ver:"
echo "✓ Authentication successful"
echo "✓ Device registered"
echo ""
echo "# Probar autenticación HTTP"
echo "cd /home/reimon/greenhouse/backend-websocket-update"
echo "./test-auth.sh"
echo ""
echo "=========================================="
echo "SI NO TIENES ACCESO AL VPS AÚN:"
echo "=========================================="
echo ""
echo "El ESP32 YA está configurado con autenticación."
echo "El sistema seguirá funcionando normalmente hasta que"
echo "despliegues el backend actualizado."
echo ""
echo "Cuando tengas acceso al VPS, ejecuta los pasos 1-4."
echo ""
echo "Token guardado en:"
echo "  - ESP32: include/secrets.h"
echo "  - Backend: backend-websocket-update/.env"
echo ""
echo "=========================================="

