version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Frontend
      - "8080:8080"  # Backend/WebSocket
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/greenhouse
      - ESP32_AUTH_TOKEN=esp32_gh_prod_tk_9f8e7d6c5b4a3210fedcba9876543210abcdef1234567890
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
    depends_on:
      - mongodb
    volumes:
      - ./backend-websocket-update/.env:/app/backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=greenhouse

volumes:
  mongodb_data: