name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-esp32:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PlatformIO
        run: pip install --upgrade platformio
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
      - name: Build greenhouse environment
        run: pio run -e greenhouse
      - name: Build VPS client environment
        run: pio run -e greenhouse-vps-client
