#!/bin/bash
# QUICK DEPLOYMENT - Ejecutar cuando recuperes la contraseña

echo "═══════════════════════════════════════════════════════════"
echo "  🌱 GREENHOUSE DASHBOARD - DEPLOYMENT RÁPIDO"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📦 Archivos listos:"
echo "   - greenhouse-frontend.tar.gz (250KB) ✓"
echo "   - vps-setup.sh (script de configuración VPS) ✓"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo "PASO 1: Subir frontend al VPS"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "scp -P 5591 greenhouse-frontend.tar.gz root@reimon.dev:/tmp/"
echo ""
read -p "Presiona ENTER cuando hayas ejecutado el comando anterior..."
echo ""

echo "─────────────────────────────────────────────────────────────"
echo "PASO 2: Subir script de configuración"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "scp -P 5591 vps-setup.sh root@reimon.dev:/tmp/"
echo ""
read -p "Presiona ENTER cuando hayas ejecutado el comando anterior..."
echo ""

echo "─────────────────────────────────────────────────────────────"
echo "PASO 3: Conectarse al VPS y ejecutar setup"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Ejecuta estos comandos EN EL VPS:"
echo ""
echo "ssh -p 5591 root@reimon.dev"
echo ""
echo "# Una vez conectado:"
echo "chmod +x /tmp/vps-setup.sh"
echo "bash /tmp/vps-setup.sh"
echo ""
read -p "Presiona ENTER cuando hayas ejecutado el setup..."
echo ""

echo "─────────────────────────────────────────────────────────────"
echo "PASO 4: Verificar deployment"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Abre en tu navegador:"
echo ""
echo "  🌐 http://reimon.dev/"
echo ""
echo "Deberías ver:"
echo "  ✓ Tarjetas de sensores con datos del ESP32"
echo "  ✓ Controles de 4 relés"
echo "  ✓ Gráficos históricos"
echo "  ✓ Gestor de reglas"
echo "  ✓ Visor de logs"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo "COMANDOS ÚTILES"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "# Ver logs del API:"
echo "pm2 logs greenhouse-api"
echo ""
echo "# Reiniciar API:"
echo "pm2 restart greenhouse-api"
echo ""
echo "# Ver status:"
echo "pm2 status"
echo "systemctl status nginx"
echo ""
echo "# Ver datos en MongoDB:"
echo "mongosh"
echo "use greenhouse"
echo "db.sensor_readings.find().sort({timestamp:-1}).limit(5)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  ✅ DEPLOYMENT COMPLETADO"
echo "═══════════════════════════════════════════════════════════"
